const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // ---------------------------------------------------------------
    // Phase 1: Bootstrap — build the harbour compiler from pure C
    // ---------------------------------------------------------------

    const hbcommon = addCLib(b, "hbcommon", "src/common", common_srcs, target, optimize);
    const hbnortl = addCLib(b, "hbnortl", "src/nortl", &.{"nortl.c"}, target, optimize);
    const hbpp = addCLib(b, "hbpp", "src/pp", pp_srcs, target, optimize);

    // The compiler library needs the pre-generated parser.
    // harbour.yyc is a C file with a non-standard extension — copy it so zig
    // recognizes it.
    const hbcplr = addCLib(b, "hbcplr", "src/compiler", compiler_srcs, target, optimize);
    const copy_parser_c = b.addSystemCommand(&.{ "cp", "src/compiler/harbour.yyc", "src/compiler/harboury.c" });
    const copy_parser_h = b.addSystemCommand(&.{ "cp", "src/compiler/harbour.yyh", "src/compiler/harboury.h" });
    hbcplr.addCSourceFile(.{
        .file = b.path("src/compiler/harboury.c"),
        .flags = harbour_cflags,
    });
    // Compiler sources include local headers (harboury.h, y_tab.h)
    hbcplr.addIncludePath(b.path("src/compiler"));
    hbcplr.step.dependOn(&copy_parser_c.step);
    hbcplr.step.dependOn(&copy_parser_h.step);

    // harbour executable
    const harbour = b.addExecutable(.{
        .name = "harbour",
        .target = target,
        .optimize = optimize,
    });
    harbour.addCSourceFile(.{
        .file = b.path("src/main/harbour.c"),
        .flags = harbour_cflags,
    });
    harbour.addIncludePath(b.path("include"));
    harbour.linkLibrary(hbcplr);
    harbour.linkLibrary(hbpp);
    harbour.linkLibrary(hbnortl);
    harbour.linkLibrary(hbcommon);

    // System libraries
    const os = target.result.os.tag;
    if (os == .windows) {
        harbour.linkSystemLibrary("kernel32");
        harbour.linkSystemLibrary("user32");
        harbour.linkSystemLibrary("ws2_32");
        harbour.linkSystemLibrary("winmm");
    } else {
        harbour.linkSystemLibrary("m");
    }
    harbour.linkLibC();

    b.installArtifact(harbour);

    // ---------------------------------------------------------------
    // Steps
    // ---------------------------------------------------------------

    const run_step = b.step("run", "Run the harbour compiler");
    const run_cmd = b.addRunArtifact(harbour);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }
    run_step.dependOn(&run_cmd.step);
}

// ---------------------------------------------------------------
// Helper: create a static library from C sources in a directory
// ---------------------------------------------------------------

fn addCLib(
    b: *std.Build,
    name: []const u8,
    root: []const u8,
    srcs: []const []const u8,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
) *std.Build.Step.Compile {
    const lib = b.addStaticLibrary(.{
        .name = name,
        .target = target,
        .optimize = optimize,
    });
    lib.addCSourceFiles(.{
        .root = b.path(root),
        .files = srcs,
        .flags = harbour_cflags,
    });
    lib.addIncludePath(b.path("include"));
    lib.linkLibC();
    return lib;
}

// ---------------------------------------------------------------
// Compiler flags — match config/linux/gcc.mk
// ---------------------------------------------------------------

const harbour_cflags: []const []const u8 = &.{
    "-Wall",
    "-W",
    "-O3",
};

// ---------------------------------------------------------------
// Source file lists — one const per library
// ---------------------------------------------------------------

const common_srcs: []const []const u8 = &.{
    "expropt1.c",
    "expropt2.c",
    "funcid.c",
    "hbarch.c",
    "hbdate.c",
    "hbffind.c",
    "hbfopen.c",
    "hbfsapi.c",
    "hbgete.c",
    "hbhash.c",
    "hbmem.c",
    "hbprintf.c",
    "hbstrbm.c",
    "hbstr.c",
    "hbtrace.c",
    "hbver.c",
    "hbverdsp.c",
    "hbwin.c",
    "hbwince.c",
    "strwild.c",
};

// Note: hbpp.c is the standalone preprocessor binary, not part of the library.
// pptable.c is pre-generated by hbpp from include/hbstdgen.ch — contains the
// standard preprocessor rule table (hb_pp_setStdRules).
const pp_srcs: []const []const u8 = &.{
    "pptable.c",
    "ppcore.c",
    "pplib.c",
    "pplib2.c",
};

const compiler_srcs: []const []const u8 = &.{
    "cmdcheck.c",
    "compi18n.c",
    "complex.c",
    "expropta.c",
    "exproptb.c",
    "genc.c",
    "gencc.c",
    "genhrb.c",
    "hbcmplib.c",
    "hbcomp.c",
    "hbdbginf.c",
    "hbdead.c",
    "hbfix.c",
    "hbfunchk.c",
    "hbgenerr.c",
    "hbident.c",
    "hblbl.c",
    "hbmain.c",
    "hbopt.c",
    "hbpcode.c",
    "hbstripl.c",
    "hbusage.c",
    "ppcomp.c",
};
