/*
 * Drydock .hrb Embedding Tool
 *
 * Reads one or more .hrb files and generates a C source file that
 * embeds them as static byte arrays with a registration function.
 *
 * Usage: hrbembed [-o output.c] file1.hrb [file2.hrb ...]
 *
 * The generated C file contains:
 * - Static byte arrays for each .hrb module
 * - dd_hrbLoadEmbedded() function that loads all modules at startup
 *
 * Copyright 2026 Teo Fonrouge <tfonrouge@gmail.com>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static char * basename_noext( const char * path )
{
   const char * p = path;
   const char * last = path;
   const char * dot = NULL;
   char * result;
   int len;

   while( *p )
   {
      if( *p == '/' || *p == '\\' )
         last = p + 1;
      if( *p == '.' )
         dot = p;
      p++;
   }
   if( dot && dot > last )
      len = ( int )( dot - last );
   else
      len = ( int )( p - last );

   result = ( char * ) malloc( len + 1 );
   memcpy( result, last, len );
   result[ len ] = '\0';

   /* sanitize: replace non-alnum with _ */
   {
      char * q;
      for( q = result; *q; q++ )
      {
         if( !( ( *q >= 'a' && *q <= 'z' ) || ( *q >= 'A' && *q <= 'Z' ) ||
                 ( *q >= '0' && *q <= '9' ) || *q == '_' ) )
            *q = '_';
      }
   }

   return result;
}

int main( int argc, char * argv[] )
{
   FILE * fout;
   const char * szOutput = NULL;
   char ** hrbFiles = NULL;
   char ** hrbNames = NULL;
   int nFiles = 0;
   int i, j;

   /* parse arguments */
   for( i = 1; i < argc; i++ )
   {
      if( strcmp( argv[ i ], "-o" ) == 0 && i + 1 < argc )
      {
         szOutput = argv[ ++i ];
      }
      else
      {
         nFiles++;
         hrbFiles = ( char ** ) realloc( hrbFiles, nFiles * sizeof( char * ) );
         hrbNames = ( char ** ) realloc( hrbNames, nFiles * sizeof( char * ) );
         hrbFiles[ nFiles - 1 ] = argv[ i ];
         hrbNames[ nFiles - 1 ] = basename_noext( argv[ i ] );
      }
   }

   if( nFiles == 0 )
   {
      fprintf( stderr, "Drydock .hrb Embedding Tool\n" );
      fprintf( stderr, "Usage: hrbembed [-o output.c] file1.hrb [file2.hrb ...]\n" );
      return 1;
   }

   fout = szOutput ? fopen( szOutput, "w" ) : stdout;
   if( !fout )
   {
      fprintf( stderr, "Error: cannot open '%s' for writing\n", szOutput );
      return 1;
   }

   /* header */
   fprintf( fout, "/* Auto-generated by Drydock hrbembed — do not edit */\n\n" );
   fprintf( fout, "#include \"hbapi.h\"\n" );
   fprintf( fout, "#include \"hbvm.h\"\n\n" );

   /* emit each .hrb as a byte array */
   for( i = 0; i < nFiles; i++ )
   {
      FILE * fin = fopen( hrbFiles[ i ], "rb" );
      unsigned char buf[ 4096 ];
      size_t nRead;
      int col = 0;
      long nTotal = 0;

      if( !fin )
      {
         fprintf( stderr, "Error: cannot open '%s'\n", hrbFiles[ i ] );
         if( szOutput ) fclose( fout );
         return 1;
      }

      fprintf( fout, "static const HB_BYTE s_hrb_%s[] = {\n   ", hrbNames[ i ] );

      while( ( nRead = fread( buf, 1, sizeof( buf ), fin ) ) > 0 )
      {
         for( j = 0; j < ( int ) nRead; j++ )
         {
            if( col > 0 ) fprintf( fout, "," );
            if( col >= 16 )
            {
               fprintf( fout, "\n   " );
               col = 0;
            }
            fprintf( fout, "0x%02X", buf[ j ] );
            col++;
            nTotal++;
         }
      }

      fprintf( fout, "\n};\n\n" );
      fclose( fin );

      fprintf( stderr, "  %s: %ld bytes\n", hrbFiles[ i ], nTotal );
   }

   /* emit loader function */
   fprintf( fout, "/* Load all embedded .hrb modules into the VM */\n" );
   fprintf( fout, "void dd_hrbLoadEmbedded( void )\n" );
   fprintf( fout, "{\n" );

   for( i = 0; i < nFiles; i++ )
   {
      fprintf( fout, "   hb_hrbLoad( ( const char * ) s_hrb_%s, sizeof( s_hrb_%s ), 0, \"%s\" );\n",
               hrbNames[ i ], hrbNames[ i ], hrbFiles[ i ] );
   }

   fprintf( fout, "}\n" );

   if( szOutput )
   {
      fclose( fout );
      fprintf( stderr, "Generated %s with %d embedded module(s)\n", szOutput, nFiles );
   }

   /* cleanup */
   for( i = 0; i < nFiles; i++ )
      free( hrbNames[ i ] );
   free( hrbFiles );
   free( hrbNames );

   return 0;
}
